=== VerkhovtsovPavel/BSUIR_Labs/WT/WT-5/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bsuir.by/pavelVerk/menu"
	xmlns:tns="http://www.bsuir.by/pavelVerk/menu" elementFormDefault="qualified">

	<element name="menu">
		<complexType>
			<sequence>
				<element name="dish" type="tns:Dish" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Dish">
		<sequence>
			<element name="name" type="string" />
			<element name="cost">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0" />
						<maxInclusive value="5000" />
					</restriction>
				</simpleType>
			</element>
			<element name="ingredients" type="tns:Ingredients" />
			<element name ="class">
				<simpleType>
					<restriction base="string">
						<enumeration value="First course"/> 
        				<enumeration value="Main course"/>
        				<enumeration value="Dessert"/>
					</restriction>
				</simpleType>
			</element>	
		</sequence>
		<attribute name="id" type="ID" use="required" />
	</complexType>

	<complexType name="Ingredients">
		<sequence>
			<element name="ingredient" minOccurs="1"
				maxOccurs="unbounded">
				<simpleType>
					<restriction base="string">
						<pattern value="[\w\d ]+" />
					</restriction>
				</simpleType>
			</element>

		</sequence>
	</complexType>
</schema>

=== VerkhovtsovPavel/BSUIR_Labs/menu.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bsuir.by/pavelVerk/menu menu.xsd" xmlns="http://www.bsuir.by/pavelVerk/menu">
   <dish id="1">
      <name>Borsch</name>
      <cost>100</cost>
      <ingredients>
         <ingredient>Salt</ingredient>
         <ingredient>Potato</ingredient>
         <ingredient>Beet</ingredient>
         <ingredient>Cabbage</ingredient>
      </ingredients>
   </dish>
   <dish id="2">
      <name>Steak</name>
      <cost>400</cost>
      <ingredients>
         <ingredient>Salt</ingredient>
         <ingredient>Beef</ingredient>
         <ingredient>Olive oil</ingredient>
      </ingredients>
   </dish>
   <dish id="3">
      <name>Caesar salad</name>
      <cost>120</cost>
      <ingredients>
         <ingredient>Salt</ingredient>
         <ingredient>Feta cheese</ingredient>
         <ingredient>Olives</ingredient>
         <ingredient>Olive oil</ingredient>
      </ingredients>
   </dish>
   <dish id="4">
      <name>Vanilla ice cream</name>
      <cost>80</cost>
      <ingredients>
         <ingredient>Milk</ingredient>
         <ingredient>Sugar</ingredient>
         <ingredient>Vanilla</ingredient>
      </ingredients>
   </dish>
</menu>
